### ISSUE TITLE
Colored text usage?

### ISSUE THREAD

**Issue by rowan-mcalpin** [PixelatedLagg/teric#1]
Hi Lagg

When reading main.cpp, I see a `PrintColored` method that is never used. You also use dye::color a lot. Did you mean to use PrintColored in the code?

@PixelatedLagg 

-Fellow programmer REMCodes

**Comment by rowan-mcalpin** [comment]
Review my PR to see changes.

**Comment by PixelatedLagg** [comment]
Hello, `PrintColored` is intended for use when I finish networking and allow for multicolored messaging between users. The point of the integer parameter is to skip any annoying color checks or possible server work and instead allow the server to store a number that represents the user's color when they send messages. This number would be sent back to the client on communication and run through `PrintColored` to easily print a message through the method. Running through a conditional when the color of a user's own nickname is constant is useless.
